# Project: trabalho-1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Users/denis/Downloads/Dev-CppPortable/Dev-CppPortable/App/devcpp/lib" -mwindows -lopengl32 
INCS =  -I"C:/Users/denis/Downloads/Dev-CppPortable/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/denis/Downloads/Dev-CppPortable/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/denis/Downloads/Dev-CppPortable/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/denis/Downloads/Dev-CppPortable/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/denis/Downloads/Dev-CppPortable/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/denis/Downloads/Dev-CppPortable/Dev-CppPortable/App/devcpp/include" 
BIN  = trabalho-1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before trabalho-1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "trabalho-1.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
